# Core shell and development tools
brew "atuin"
brew "bat"
brew "bottom"
brew "chezmoi"
brew "delta"
brew "direnv"
brew "dust"
brew "duf"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "hyperfine"
brew "jq"
brew "just"
brew "lazygit"
brew "mise"
brew "ripgrep"
brew "starship"
brew "tealdeer"
brew "tmux"
brew "tokei"
brew "tree"
brew "watchexec"
brew "wget"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# iOS development support. Xcode itself remains App Store-managed.
brew "xcbeautify"

cask "font-jetbrains-mono-nerd-font"
